//
//  WeatherViewController.swift
//  Test
//
//  Created by Сергей Вихляев on 25/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//484638
//https://openweathermap.org/current   

protocol WeatherDisplayLogic: BaseViewProtocol, BaseViewNavigationProtocol {
}

class WeatherViewController: UIViewController, WeatherDisplayLogic {

    fileprivate let tambovID: Int = 484638

    var navController: UINavigationController?
    static var kStoryboardID: String = String(describing: WeatherViewController.self)

    enum Texts: String {
        case title = "Погода"
    }

    // MARK: Params
    var presenter: WeatherPresentationLogic?


    // MARK: Lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavigationController()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        presenter?.getCurrentWeatherForCity(with: tambovID)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setupVC()
    }
    // MARK: Setup
    private func setupVC() {
        // TextFields
        //delegating()

        // Keyboard
        //setupObserving()
        //setupGestures()

    }

    private func setupNavigationController() {
        self.title = Texts.title.rawValue
    }

    func showInfoAlert(_ info: String) {

    }

    func showErrorAlert(_ error: Error) {

    }
}
