//
//  WeatherViewController.swift
//  Test
//
//  Created by Сергей Вихляев on 25/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//484638
//https://openweathermap.org/current   

protocol WeatherDisplayLogic: BaseViewProtocol, BaseViewNavigationProtocol {
    func showAllT(current: String, min: String, max: String)
}

class WeatherViewController: UIViewController, WeatherDisplayLogic {

    fileprivate let tambovID: Int = 484638

    var navController: UINavigationController?
    static var kStoryboardID: String = String(describing: WeatherViewController.self)

    enum Texts: String {
        case title = "Погода"
    }

    // MARK: IBs
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var currentTLabel: UILabel!
    @IBOutlet weak var mitTLabel: UILabel!
    @IBOutlet weak var maxTLabel: UILabel!

    // MARK: Params
    var presenter: WeatherPresentationLogic?
    var reloadButton: UIBarButtonItem?

    // MARK: Lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavigationController()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        presenter?.getCurrentWeatherForCity(with: tambovID)
        activityIndicator.startAnimating()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setupVC()
    }
    // MARK: Setup
    private func setupVC() {
        // TextFields
        //delegating()

        // Keyboard
        //setupObserving()
        //setupGestures()

    }

    private func setupNavigationController() {
        self.title = Texts.title.rawValue
        if reloadButton == nil {
            reloadButton = UIBarButtonItem(barButtonSystemItem: .refresh, target: self, action: #selector(reloadT))
        }
        navigationItem.rightBarButtonItem = reloadButton
    }

    @objc func reloadT() {
        activityIndicator.startAnimating()
        presenter?.getCurrentWeatherForCity(with: tambovID)
    }

    // MARK: Logic
    func showAllT(current: String, min: String, max: String) {
        activityIndicator.stopAnimating()
        currentTLabel.text = current
        mitTLabel.text = min
        maxTLabel.text = max
    }

    func showInfoAlert(_ info: String) {
        activityIndicator.stopAnimating()
        showAlert(withInfo: info)
    }

    func showErrorAlert(_ error: Error) {
        activityIndicator.stopAnimating()
        showAlert(withError: error)
    }
}
