//
//  WeatherPresenter.swift
//  Test
//
//  Created by Сергей Вихляев on 25/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherPresentationLogic {
}

class WeatherPresenter: WeatherPresentationLogic {
    var viewController: WeatherDisplayLogic?
    var interactor: WeatherBusinessLogic?
}
