//
//  WeatherPresenter.swift
//  Test
//
//  Created by Сергей Вихляев on 25/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherPresentationLogic {
    func getCurrentWeatherForCity(with id: Int)
}

class WeatherPresenter: WeatherPresentationLogic {

    var viewController: WeatherDisplayLogic?
    var interactor: WeatherBusinessLogic?

    func getCurrentWeatherForCity(with id: Int) {
        interactor?.getWeatherForCity(with: id, completion: { (success, main, message, error) in
            if success {
                guard let current = main?.temp, let min = main?.tempMin, let max = main?.tempMax else {
                    fatalError("main is empty")
                }
                self.viewController?.showAllT(current: "\(Int(current))", min: "\(Int(min))", max: "\(Int(max))")
            } else {
                if message != nil {
                    self.viewController?.showInfoAlert(message!)
                } else if error != nil {
                    self.viewController?.showErrorAlert(error!)
                } else {
                    fatalError("message & error is empty")
                }
            }
        })
    }
}
