//
//  EnterViewController.swift
//  Test
//
//  Created by Сергей Вихляев on 24/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EnterDisplayLogic: BaseViewNavigationProtocol {
}

class EnterViewController: UIViewController, EnterDisplayLogic {

    static var kStoryboardID: String = String(describing: EnterViewController.self)

    // Texts
    enum Texts: String {
        case title = "Некий контроллер"
    }

    // MARK: EnterDisplayLogic
    var navController: UINavigationController?

    // MARK: Params
    var presenter: EnterPresentationLogic?

    // MARK: IBs
    @IBAction func authButtonWasPressed(_ sender: UIButton) {
        presenter?.goToAuth()
    }

    // MARK: Lifecycle

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.title = Texts.title.rawValue
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setupVC()
        //...
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.title = ""
    }

    private func setupVC() {
        preparing()
        //...
    }

    private func preparing() {
        navController = navigationController
    }
}
