//
//  EnterRouter.swift
//  Test
//
//  Created by Сергей Вихляев on 24/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EnterRoutingLogic {
    func routeTo(target: EnterRouter.Targets, usingNC: UINavigationController?)
}

class EnterRouter: EnterRoutingLogic {

    enum Targets {
        case authorization
        // ...
    }

    func routeTo(target: EnterRouter.Targets, usingNC: UINavigationController?) {
        switch target {
        case .authorization:
            let authVC = AuthorizationViewController(nibName: AuthorizationViewController.kStoryboardID, bundle: nil)
            AuthorizationConfigurator().configure(viewController: authVC)
            usingNC?.pushViewController(authVC, animated: true)
        }
    }
}
