//
//  EnterPresenter.swift
//  Test
//
//  Created by Сергей Вихляев on 24/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EnterPresentationLogic {
    // MARK: Routing part
    func goToAuth()
}

class EnterPresenter: EnterPresentationLogic {
    var viewController: EnterDisplayLogic?
    var interactor: EnterBusinessLogic?
    var router: EnterRoutingLogic?

    // MARK: Routing part
    func goToAuth() {
        router?.routeTo(target: .authorization)
    }
}
