//
//  AutorizationPresenter.swift
//  Test
//
//  Created by Сергей Вихляев on 24/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationPresentationLogic {
    func emailWasChanged(currentEmail: String)
    func passwordWasChanged(currentPassword: String)

    func fogotPasswordButtonWasPressed()
    func loginWasPressed()
    func createAccountButtonWasPressed()
}

protocol AuthorizationDataStore {
    var email: String { get set }
    var password: String { get set }
}

class AuthorizationPresenter: AuthorizationPresentationLogic, AuthorizationDataStore {

    enum Texts: String {
        case fogotPassword = "Переход в форму восстановления пароля"
        case createAccount = "Переход в форму создания аккаунта"
    }

    var viewController: AuthorizationDisplayLogic?
    var interactor: AuthorizationBusinessLogic?
    var router: AuthorizationRoutingLogic?

    // MARK: AuthorizationDataStore
    var email: String = ""
    var password: String = ""

    // MARK: Params
    var validator = Validator()

    // MARK: AuthorizationPresentationLogic
    func emailWasChanged(currentEmail: String) {
        email = currentEmail
        checkRules()
    }

    func passwordWasChanged(currentPassword: String) {
        password = currentPassword
        checkRules()
    }

    // MARK: Logic
    private func checkRules() {
        if validator.isValidEmail(text: email) && validator.isValidPassword(text: password) {
            viewController?.allowLogin()
        } else {
            viewController?.denyLogin()
        }
    }

    // MARK: Routing
    func createAccountButtonWasPressed() {
        //router?.routeTo(target: .createAccount, usingNC: viewController?.navController)
        viewController?.showInfoAlert(Texts.createAccount.rawValue)
    }

    func fogotPasswordButtonWasPressed() {
        //router?.routeTo(target: .fogotPassword, usingNC: viewController?.navController)
        viewController?.showInfoAlert(Texts.fogotPassword.rawValue)
    }

    func loginWasPressed() {
        router?.routeTo(target: .weather)
    }
}


