//
//  AutorizationRouter.swift
//  Test
//
//  Created by Сергей Вихляев on 24/02/2019.
//  Copyright (c) 2019 Сергей Вихляев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationRoutingLogic {
    func routeTo(target: AuthorizationRouter.Targets, usingNC: UINavigationController?)
}

class AuthorizationRouter: AuthorizationRoutingLogic  {

    enum Targets {
        case weather, createAccount, fogotPassword
    }

    func routeTo(target: AuthorizationRouter.Targets, usingNC: UINavigationController?) {
        switch target {
        case .weather:
            let authVC = WeatherViewController(nibName: WeatherViewController.kStoryboardID, bundle: nil)
            WeatherConfigurator().configure(viewController: authVC)
            usingNC?.pushViewController(authVC, animated: true)
        case .createAccount:
            print("")
            // ...
        case .fogotPassword:
            print("")
            // ...
        }
    }
}
